### PR TITLE
Feat/add issue templates

### PR DESCRIPTION
**Pull request by masaaki-uesaka**
## Scope of PR
- Add issue templates
- Edit PR template to more simplified version.
- cf. https://www.notion.so/arithmer/PR-Issue-template-f5cae8ae45484eaeae20c95e000f901a

## Major changes in codes/documents
- Added three types of issue templates: Feature Requests, Refactoring and Bug Report.
- Edited PR template: the Japanese version is removed for simplification.

## What to be reviewed
- [ ] Is the code reproducible?
  - [ ] Can you reproduce the result with the instructions in `README.md`?
    - [ ] Does it have a link to the necessary files (training data/trained model)?
    - [ ] Is a virtual environment (such as`poetry`/`docker`) set up?
    - [ ] Is the version of all the dependencies specified? (`requirements.txt` often has this issue)
- [ ] Does the code have docstring/type annotation?
  - [ ] Are there docstring in all the methods/class?
  - [ ] Are the docstring written in appropriate format (which can be used by `mkdocs/sphinx`)?
  - [ ] Are all the methods type annotated?
- [ ] Is the code comprehensive?
  - [ ] Is the code comprehensive/clear?
  - [ ] Is the logic correct/as intended?
- [ ] Are the names for variable/method/class appropriate?
  - [ ] Is variable/method/class name meaningful? (as it is a short comment)
  - [ ] Are the names following [pep8](https://realpython.com/python-pep8/#naming-conventions)?
- [ ] Is coverage rate high enough? (if there is unittest)

## Requested deadline for review
Can you please review this PR by `2022/09/30` ?

### CODE REVIEW

**Review by Chikashi-Arita — COMMENTED** [review]
・期限は上の方がいいと思いました。
・必須項目と推奨項目で分けるのもいいかもと思いました。

**Comment by yujiro-murakami** [comment]
個人的にはDue dateは不要だと思います。
issueの使い方にもよりますが、issueをあげる段階（もしくはその人）で決めることでは無いと思います。

**Comment by Chikashi-Arita** [comment]
@yujiro-murakami さん
due date に関しては
まさにissueの使い方に依るって感じですね。。
場合によっては重要でないし、場合によってはとても重要だったりするのかなと思いました。

**Comment by yujiro-murakami** [comment]
期限を管理するならマイルストーン使うのもありだと思います。
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones

**Comment by masaaki-uesaka** [comment]
@Chikashi-Arita @yujiro-murakami だいぶ時間が空いてしまいましたが，issue templateについて，Due Dateは消すことにしました．

**Review by Chikashi-Arita — APPROVED** [review]
だいぶ時間が空いてしまいましたが、approve します。

**Pull request merged**
